"""add status data

Revision ID: 00115dd88371
Revises: 95c5c18b57b8
Create Date: 2026-01-09 15:26:29.162192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00115dd88371'
down_revision: Union[str, Sequence[str], None] = '95c5c18b57b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            'conversion_status',
            sa.column('id', sa.Integer),
            sa.column('status_name', sa.String),
        ),
        [
            {'id': 1, 'status_name': 'pending'},
            {'id': 2, 'status_name': 'processing'},
            {'id': 3, 'status_name': 'completed'},
            {'id': 4, 'status_name': 'failed'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute ("DELETE FROM conversion_status WHERE id IN (1, 2, 3, 4)")
    # ### end Alembic commands ###
